[package]
name = "receipts"
version = "0.1.1"
edition = "2024"
authors = ["Andy Terra <spam@andyterra.com>"]
contributors = ["John Grs <johnpgrs@gmail.com>"]

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "debug"] }
